# Generated by Django 5.0.3 on 2025-06-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_remove_donor_contact_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
