# Generated by Django 5.0.3 on 2025-06-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_donation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
