# Generated by Django 5.0.3 on 2025-07-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0006_alter_donation_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='Cnic',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
