# Generated by Django 5.0.3 on 2025-07-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0007_alter_volunteer_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
