# Generated by Django 5.0.3 on 2025-07-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0009_alter_volunteer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationarea',
            name='volunteers',
            field=models.ManyToManyField(blank=True, to='donate.volunteer'),
        ),
    ]
