# Generated by Django 5.0.3 on 2025-07-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0010_donationarea_volunteers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=15)),
                ('cnic', models.CharField(blank=True, max_length=13, null=True)),
                ('family_members', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('date_received', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
