# Generated by Django 5.0.3 on 2025-07-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0011_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='father_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='status',
            field=models.CharField(blank=True, choices=[('Widow', 'Widow'), ('Orphan', 'Orphan'), ('Poor', 'Poor')], default='poor', max_length=20),
        ),
    ]
