# Generated by Django 5.0.3 on 2025-07-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0013_remove_volunteer_cnic_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(default='Unpaid', max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='adminpic',
            field=models.FileField(blank=True, null=True, upload_to='admin_images/'),
        ),
    ]
